### ISSUE TITLE
LanguageTool triggers SwayLock

### ISSUE THREAD

**Issue by ignamartinoli** [vigoux/LanguageTool.nvim#18]
**Describe the bug**
Super weird. When I run `:LanguageToolSetUp` **Neovim** returns that the server started. Then when I run `:LanguageToolCheck`, `swaylock` activates with a white lock screen. When I log in back again, another blank window has been created and if I close it on **Neovim** I receive the message:

    Error detected while processing function LanguageTool#server#sendCallback:
    line    2:
    E474: Unidentified byte: Error: Could not parse JSON from 'data' parameter

If I try to use this plugin on **LaTeX** files, I can get to start the server but it doesn't detected any errors when I run `:LanguageToolCheck` or `:LanguageToolSummary`.

**To Reproduce**
1. Open a **Mardown** file in **Neovim**
2. Run `:LanguageToolSetUp`
3. Run `:LanguageToolCheck`

**Expected behavior**
The plugin to show the errors.

**Desktop (please complete the following information):**
 - OS: **Gentoo**
 - Browser: **Firefox**
 - Version: `NVIM v0.8.0-dev+11-gd3121f1e6-dirty`

**Comment by vigoux** [comment]
Could you tell us here what you happened to do to fix the issue?
