### ISSUE TITLE
Have 'f' autofix the issue with the first recommended correction

### ISSUE THREAD

**Issue by RonanMacF** [vigoux/LanguageTool.nvim#9]
vim-grammarous is a good plugin in theory, its features are fairly nice, but it just was littered with bugs when I tried to use it. Having the ability to autofix errors by pressing 'f' would bring this closer to feature parity with grammarous. Looking at my errors a lot of the time the fix I want is the first one, so having to just move to the error and pressing 'f' on either window would be nice. 

This feature would ideally autorefresh with the fixed error then disappearing. Although with slow reading times i'm not sure how plausible this would be.

**Comment by vigoux** [comment]
`f` on the report windows already does that.
Otherwise you can use the following mapping :

```vim
nnoremap <silent> f <cmd>LanguageToolFixAtPoint<CR>
```

**Comment by RonanMacF** [comment]
ah my apologies, didn't spot that command on the README but I see it in the docs now, Cheers will close!

**Comment by vigoux** [comment]
Thanks for reporting, that is worth adding in the README anyway !
